### ISSUE TITLE
Reverse the grid

### ISSUE THREAD

**Issue by Bashirkazimi** [hannahcode/wordle#17]
Hi, 

Great project this one. I wanted to try one for Persian and I was wondering how I can show the grid in reverse order as Persian is written from right to left. It would be great if you could give me a hint :) 

Thank you so much :)

**Comment by gbear605** [comment]
If anyone else needs to do this, one solution is to set the [dir attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) on the main <html> tag to "rtl". If you want to embed a left-to-right language inside (for example, English in the about modal), you can set the dir attribute to "ltr" on just the tag that contains that language.
