### ISSUE TITLE
Disable the letters that are no longer available

### ISSUE THREAD

**Issue by szabgab** [hannahcode/wordle#22]
After trying a letter and getting it marked gray, the user should not be able to type it in any more.

(Maybe make this optional using a checkbox?)

**Comment by NeilGirdhar** [comment]
The optimal play can easily require letters that aren't available anymore.  For example, if you open with "raise", and the "i" is green, and the "e" is yellow, then a near-optimal play is "fends", which narrows the possible solutions down to two.

**Comment by szabgab** [comment]
Yeah, @NeilGirdhar , you are probably right.

**Comment by NeilGirdhar** [comment]
In case, you're interested, I wrote a solver https://github.com/NeilGirdhar/wordle-solver
