### ISSUE TITLE
Make it easy to add other languages

### ISSUE THREAD

**Issue by szabgab** [hannahcode/wordle#25]
It would be nice if other languages could use the same code base without creating their own project.

**Comment by tcuc** [comment]
I'm looking into it.

**Comment by szabgab** [comment]
You can take a look at the 'ladino' branch of my fork at https://github.com/szabgab/wordle to see which files I had to change.
The two words lists are the obvious ones and then there are some texts in a few files that need to be adjusted.
I did not need to adjust the keyboard, but other languages - even latin alphabet-based languages might need it.
