### ISSUE TITLE
Share doesn't work

### ISSUE THREAD

**Issue by Ciractt** [hannahcode/wordle#43]
Share doesn't seem to be working for me. You click it and it does nothing on both mobile & desktop devices. Isn't it meant to copy to clipboard?

**Comment by GoodCrossing** [comment]
Is the web server using HTTPS? It won't work with HTTP.

**Comment by hannahcode** [comment]
Seems to work - I'm thinking the issue might be HTTP vs HTTPS like @samuel-rey mentioned. Closing for now.
