### ISSUE TITLE
How to play/execution discrepancy

### ISSUE THREAD

**Issue by pg-tern** [hannahcode/wordle#45]
Rules say that a grey number is "not in the prime in any spot" - but when a digit is repeated in the prime, the first occurrence shows green or orange, second shows as grey. I believe it should show as orange instead.

Example I ended with (failed): 1(green) 1(grey) 4(green) 4(grey) 7(green) - all other digits grey at bottom. This leaves no digits possible, per the rules! The prime had repeated 4 and 7 I believe (I didn't write down the correct answer, not sure the order, sorry!)

**Comment by hannahcode** [comment]
Closing this - this isn't the code for Primel
