### ISSUE TITLE
Losing should permanently reveal the word

### ISSUE THREAD

**Issue by buddhist-uni** [hannahcode/wordle#47]
In "reference" Wordle, a permanent Alert pops up with the answer if you fail to get it in six tries.

**Comment by hannahcode** [comment]
With this version, losing should reveal a temporary alert with "You lost, the word was {insert winning word}". Are you at least seeing that?

**Comment by buddhist-uni** [comment]
Ah yes. It just disappeared faster than I could read it 😆 Sticky would be better. And when you hit "Enter" afted a loss, you get "not enough letters" which feels buggy.

**Comment by hannahcode** [comment]
Thanks for pointing these things out! I made a commit to have the losing modal persist and fixed the issue of "not enough letters" getting triggered on enter after a loss.
