### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by MikhaD** [hannahcode/wordle#51]
I this is not a good reason to create an issue but I wanted to comment.
I just finished working on my [own version](https://github.com/MikhaD/wordle) of a Wordle clone and checked to see if anyone else had done something similar on GitHub. This was the first repo to come up. Looks like you got there a few weeks ahead of me.
I also used Typescript and a front end framework :)

**Comment by dubeyji10** [comment]
yeah she did a great job

**Comment by hannahcode** [comment]
Thanks @MikhaD - your version looks really good! Closing this, I appreciate the nice comments :)
