### ISSUE TITLE
Make string constants file

### ISSUE THREAD

**Issue by buddhist-uni** [hannahcode/wordle#56]
For those of us making international (non-English) versions of Wordle with this project as our base, the recent refactor of the Modals is a bit of a pain to rebase, as all the translated strings need to be rebased by hand.  This problem can be solved by putting UI strings into a constants file, where people translating the app can make their changes independent of code refactors.

**Comment by hannahcode** [comment]
I think a recent PR solves this - feel free to open a new issue if not! Closing for now.

**Comment by buddhist-uni** [comment]
Sure, just have to remember to move strings over as theyre touched by code changes (which my PR was also guilty of not doing 😬)
