### ISSUE TITLE
Stop exposing the possible words

### ISSUE THREAD

**Issue by soumendrak** [hannahcode/wordle#58]
- Is there any way we can hide the words used in the game from users?
- For example in Firefox, if I go to Inspect -> Debugger tab I can see all the possible words that can be answered. 
- How does the original game hide it?
- Screenshot for reference:
![words-exposed](https://user-images.githubusercontent.com/10120538/150727274-cab7a83b-f456-42ca-8c7e-7ffc829ecc23.png)

**Comment by DavidPatzke** [comment]
Hey,

like in the readme is stated: The original game does not hide the list in any way. It is just a plain array in the source code.

**Comment by dubeyji10** [comment]
hey soumendrak
you are seeing all the combination possible (not really a powerup is it ?)
like i do when i use an anagram generator( to cheat yeah :p )

**Comment by diondiondion** [comment]
I wouldn't bother to "fix" this. Wordle is a game you play against yourself, why prevent people from spoiling their own fun? 😛

Also, they could always navigate to this Github repo from the About window and look up the solution in the code.

**Comment by syedusmanzafar** [comment]
hey, i added my own words on the wordlist.ts now the browser is showing me blank page why is it so?

**Comment by hannahcode** [comment]
Based on the conversation here I'm closing this for now, thanks everyone!
