### ISSUE TITLE
Missing Valid Words

### ISSUE THREAD

**Issue by chrsking** [hannahcode/wordle#6]
Hey, first up this is fantastic. Been playing around trying to make my own version and was great to stumble across this.

Just thought I'd let you know, it seems to be missing part of the word list. I noticed that my first 3 guesses (roate, areas, and conga) were all not valid words, when I know they work on the normal wordle.

I had a look and I can see your words list matches the var in the wordle source code named "La", but I noted that after this list, there is a second var named "Ta" that has the rest of the words. I'm guessing one is a list of the daily words and the other is a list of valid answers?

**Comment by hannahcode** [comment]
Thanks so much @chrsking, the game currently has only the list of daily words included. If you would like to contribute to the project by adding the second list, please feel free, otherwise I will plan to add that soon!

**Comment by pip8786** [comment]
Do you need two separate lists or just make all 5 letter words a possible daily word?

**Comment by hannahcode** [comment]
I added the list of valid guesses. Thanks all!

**Comment by pip8786** [comment]
@hannahcode are those real words? A lot of them look made up :)
