### ISSUE TITLE
I added my own words on the wordlist.ts now the browser is showing me blank page why is it so?

### ISSUE THREAD

**Issue by syedusmanzafar** [hannahcode/wordle#63]
hey, i added my own words on the wordlist.ts now the browser is showing me blank page why is it so? can anyone help me in this matter?

**Comment by jahoo** [comment]
Did you just add words, or also remove some? If the total number of words is less than the index for the day, this could cause an issue.

**Comment by hannahcode** [comment]
Hopefully @jahoo's comment was helpful. If you want to start the list from index 1, you can update the `epochMs` value in [words.ts](https://github.com/hannahcode/wordle/blob/main/src/lib/words.ts) to be today since epoch in ms, which you can find here: https://www.epochconverter.com/.

**Comment by syedusmanzafar** [comment]
Another thing site always shows one word for winning like on my side it selects a twist word and if I deleted the cookie and play the game again it still selects the same word i-e twist it should pick a random word for the next game? @hannahcode

**Comment by syedusmanzafar** [comment]
@jahoo thanks that problem  was solved much thanks

**Comment by hannahcode** [comment]
@syedusmanzafar the way the game is set up it only provides one solution word per day, so a new solution won't be available after you delete the cookies. Closing this issue for now, thanks everyone!
