### ISSUE TITLE
Won't reload page for a new turn after closing "You won" pop-up

### ISSUE THREAD

**Issue by tkoset** [hannahcode/wordle#7]

**Comment by hannahcode** [comment]
Thanks for your comment, I might be misunderstanding, but maybe this will help. In the original game the page doesn't reload after closing the win modal either. There is only one solution word per day.

**Comment by tkoset** [comment]
Thanks for the reply and good work! I wanted to play Wordle in Turkish and I found your project. I'm a graphic designer and I know nothing about React. I only know html and css:) However I somehow modified your code and add 5500 Turkish words.

https://flamboyant-swirles-9b3ae5.netlify.app/

I also researched on only-one-word-for-a-day restriction of wordle and changed mathfloor into below:

Math.floor(Math.random() * 5500)

Now it is able to give random words continuously. The only problem remains is I have to refresh the page manually. Is there an easy way to make it refresh the page after closing WinModal or You Lost alert?

**Comment by hannahcode** [comment]
Thats so awesome, thanks for sharing your version! In order to do a hard reset of the page, you can use window.location.reload() in the win modal and in the logic for a lost game.

**Comment by tkoset** [comment]
Thanks. I made it worked for lost games. Now I'm trying to understand the structure of the WinModal.

**Comment by ericdrgn** [comment]
@tkoset did you ever figure out how to refresh the page via a button or something? I was able to add it to the stats modal if you still couldn't figure it out.
