### ISSUE TITLE
find a word every time

### ISSUE THREAD

**Issue by azzaba** [hannahcode/wordle#72]
we can find a solution every time with a simple breakpoint trick :)
![breakpoint](https://user-images.githubusercontent.com/8998812/151606973-5427d8d3-c5c4-4204-957f-c012f7aa42d6.jpg)

**Comment by eggplants** [comment]
This fact has also been pointed out for the original　Wordle. 
https://www.google.com/search?q=wordle+answer+reddit
This app judges the correct answer on the client side, so it is possible to cheat on the answer. If you want to check the answer, you can, but it will obviously only take away your fun of the game.

**Comment by hannahcode** [comment]
Closing this for now - thanks @eggplants for providing this explanation :)
