### ISSUE TITLE
utf8 problem 

### ISSUE THREAD

**Issue by veysel-xan** [hannahcode/wordle#76]
help me pls
` <Key value="Ü" onClick={onClick} status={charStatuses['Ü']} />
`

```
10:07:19 PM: Failed to compile.
10:07:19 PM: 
10:07:19 PM: TS2322: Type '"Ü"' is not assignable to type 'KeyValue'.

10:07:19 PM:   > 50 |         <Key value="Ü" onClick={onClick} status={charStatuses['W']} />
```

**Comment by gbear605** [comment]
You'll have to add all characters that aren't found in English to the type `CharValue` in the `src/lib/statuses.ts` file. You'll likewise want to remove any characters that you aren't using from that type.

**Comment by veysel-xan** [comment]
how ?
