### ISSUE TITLE
Cannot type / (slash) in Firefox

### ISSUE THREAD

**Issue by han-kwang** [hannahcode/wordle#80]
Firefox (Linux) captures the / key as the shortcut for search, so divisions are only possible using the on-screen keyboard.

**Comment by diondiondion** [comment]
Why would you need to type divisions in Wordle?

**Comment by han-kwang** [comment]
Sorry, my bad. This repo was linked from a numerical Wordle variant, https://nerdlegame.com/ (under the info button), but I misunderstood; it only said that it forked this wordle clone. I should have read it more carefully.
